Remove ProgramsView from students learning menu; Add autofail_ungraded functional and tests
cscenter/lms pull request #800
Opened 2024-01-26 14:01 UTC by Dmi4er4

# Checklist:

- [ ] I have performed a self-review of my own code:
    - [ ] Good naming: make sure you would understand your code if you read it a few months from now.
    - [ ] No common performance issues (e.g. N + 1 problem)
    - [ ] Unrelated code has been removed (unused imports, `print` statements, unrelated template context variables, commented code, etc)
    - [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I understand that short PRs lead to higher-quality code and faster delivery of features.
- [ ] Linear history: my code has been rebased on the most recent commit in the master branch before opening PR
- [ ] I have followed [conventional commits specification](https://www.conventionalcommits.org/) for PR title
- [ ] I have referenced YouTrack issue in the PR description for easy access
- [ ] I have added tests that prove my code works

2024-01-31 17:36 UTC, atolstikov requested changes

2024-01-31 17:36 UTC, atolstikov commented on apps/projects/management/commands/autofail_ungraded.py
> +    Set --prev-sem flag to apply for courses from Autumn 2020 till previous semester.
Зачем реализована такая странная логика? Почему в этом случае явно не запрашивать указание семестра?

2024-01-31 17:36 UTC, atolstikov commented on apps/projects/management/commands/autofail_ungraded.py
> +        graded = enrollments.update(grade=GradeTypes.UNSATISFACTORY)
Хорошо бы записать куда-то в лог, что было изменено. Пусть даже операция без отката, но у тебя хоть какой-то будет механизм восстановления.

2024-01-31 17:36 UTC, atolstikov commented on apps/staff/urls.py
> +    autofail_ungraded, create_alumni_profiles
Стиль именования этих view отличается, стоит сделать тоже CamelCase

2024-01-31 17:36 UTC, atolstikov commented on apps/staff/views.py
> +            request, f"Операция выполнена успешно.<br>" f"Выставлено незачетов: {graded}"
Тоже рекомендую выводить все кортежи: курс, семестр, фио

2024-01-31 17:36 UTC, atolstikov commented on lk_yandexdataschool_ru/menu.py
> +            # MenuItem(pgettext_lazy("menu", "Проекты организаторов"), '/learning/internships/', weight=80),
Добавить комментарий, почему решили это убрать именно таким образом.

2024-01-31 17:36 UTC, atolstikov commented on manage.py
> +                          "lk_yandexdataschool_ru.settings.local")
Почему думаешь, что так нужно сделать?

2024-01-31 17:56 UTC, Dmi4er4 commented on apps/staff/urls.py
> +    autofail_ungraded, create_alumni_profiles
Это не view, поэтому и отличается. Это кастомные команды django-admin.

2024-01-31 18:01 UTC, Dmi4er4 commented on apps/projects/management/commands/autofail_ungraded.py
> +    Set --prev-sem flag to apply for courses from Autumn 2020 till previous semester.
По аналогии с автоматическим выставлением оценок по проектам, по дефолту изменяется действующий сем. Сделано, как я понимаю, в основном в качестве защиты от дурака, чтобы невозможно было поменять наследие. Флаг придуман, чтобы можно было единократно запустить этот скрипт на проде и почистить все оценки до 2020 года. Доступа к нему нет из UI сайта.

2024-01-31 18:02 UTC, Dmi4er4 commented on apps/projects/management/commands/autofail_ungraded.py
> +    Set --prev-sem flag to apply for courses from Autumn 2020 till previous semester.
Осень 2020 года выбран как последний важный сем. Предполагается, что не существует действующих студентов, поступивших раньше.

2024-01-31 18:07 UTC, Dmi4er4 commented on manage.py
> +                          "lk_yandexdataschool_ru.settings.local")
В основном сейчас изменяется все же сайт ШАДа, поэтому имеет смысл по дефолту запускать сайт именно с настройками ЛМС ШАДа. Это означает лишь то, что в процессе разработки теперь не нужно добавлять строку  --settings=lk_yandexdataschool_ru.settings.local ко всем выполняемым командам. И не имеет влияния на продакшн.

2024-01-31 18:23 UTC, Dmi4er4 commented on apps/staff/views.py
> +            request, f"Операция выполнена успешно.<br>" f"Выставлено незачетов: {graded}"
Это сообщение, появляющееся в случае успеха в окошке в нижнем правом углу страницы. Несколько десятков кортежей туда может поместиться, но не сотни.

2024-01-31 18:29 UTC, Dmi4er4 commented on apps/staff/views.py
> +            request, f"Операция выполнена успешно.<br>" f"Выставлено незачетов: {graded}"
<img width="546" alt="image" src="https://github.com/cscenter/lms/assets/39742182/5b61bf75-978d-4230-9195-0ce2221cb3f9">

2024-01-31 19:25 UTC, atolstikov commented on apps/projects/management/commands/autofail_ungraded.py
> +    Set --prev-sem flag to apply for courses from Autumn 2020 till previous semester.
Если нужно запустить один раз, то это не должно потом храниться вечно в репозитории.

2024-01-31 19:26 UTC, atolstikov commented on apps/staff/urls.py
> +    autofail_ungraded, create_alumni_profiles
Тогда странно, что они таким образом смешиваются в импорте

2024-01-31 19:28 UTC, atolstikov commented on manage.py
> +                          "lk_yandexdataschool_ru.settings.local")
Если это изменение важно только тебе локально, то и коммитить его не нужно

2024-02-01 14:53 UTC, atolstikov approved these changes

2024-02-01 14:53 UTC, merged